### PR TITLE
[enhancement] Provides limit

### PR DESCRIPTION
**Pull request by lucasmichot**
Provides limit for the number of items to process.
Default is 0 - no limit

### CODE REVIEW

**Comment by thujohn** [comment]
Hi.

Actually I make a limit while building the feed : Articles::take(15)->get;
It's faster to limit before the treatment.

Maybe I missed something else in your code...

**Comment by lucasmichot** [comment]
True but your items can come from various sources.
Articles table, pages table, comments table and so on... IMO it remains a good option

**Comment by thujohn** [comment]
IMO ?

**Comment by lucasmichot** [comment]
In my opinion ;)

**Comment by thujohn** [comment]
OK ^^

I merge your pull request to let the choice but I think it's even better to limit before the treatment :)

**Pull request merged**
